### PR TITLE
Add separate pages for voting and viewing + add floodcheck

### PR DESCRIPTION
**Pull request by pieterdeschepper**

### CODE REVIEW

**Comment by shiffman** [comment]
Hi @pieterdeschepper I just merged @dipamsen's view pages, would you mind taking a look and re-submitting this with any improvements / changes from that pull request? Thank you so so much!!

**Comment by pieterdeschepper** [comment]
Hm, I think there are quite some incompatible changes in there (he basicaly did the same, but in another way :) ). I'll look into it later to see if I can port over any of my functionality in there.

**Comment by pieterdeschepper** [comment]
I was able to fix the merge conflicts. For now everything works again, but some more refactoring / cleanup needed later to make it more useable / consistent. Coming up later!

**Comment by shiffman** [comment]
lovely!

**Pull request merged**
