### PR TITLE
Added function to add or remove options from poll

### PR DESCRIPTION
**Pull request by abhpd**
This pull request solves #94 

- [x] Added 2 buttons to add a new option or to remove the last option.
- [x] Assigned unique colors to the buttons
- [x] Fixed some issues with css using flexbox
- [x] Changed maxOptions count to defaultOptions count

### CODE REVIEW

**Comment by abhpd** [comment]
@shiffman Please review and suggest any changes needed 😊

**Comment by shiffman** [comment]
@foxytocin If you have a minute to take a look at this?

**Review by foxytocin — COMMENTED** [review]
@shiffman Shouldn't conflict with previous PR of mine nor #101. Just checked within github. I didn't made a functional test. I can take a "final deeper look" after every new functionality is merged >> #100 and #101

**Comment by shiffman** [comment]
Great! Thanks for the contribution @abhpd! I'm taking an unusual approach with this project and pretty much merging everything! If something breaks, we'll fix it!

**Comment by abhpd** [comment]
@shiffman Yes we will ✨ Thanks for merging ❤️ 🥳 | Thanks for the review @foxytocin 😊

**Comment by foxytocin** [comment]
@shiffman #102 proves the functionality of all routes and new options feature. I updated the README to reflect all of this.

**Pull request merged**
