### PR TITLE
Pass poll id to voting page

### PR DESCRIPTION
**Pull request by jriegraf**
hello guys, i thought about how to remove the hard coded poll id from sketch.js and replace it with the id from the url.

I found a way with the [template engine pug](https://pugjs.org/). But I don't know if that's a good way to go, maybe this could be solved a lot easier. I would be happy if someone shares their thoughts on this.

### CODE REVIEW

**Comment by dipamsen** [comment]
I thought of URL query strings, i.e.
`localhost:3000?pollId=required_poll_id_here`
This won't require any changes in backend
There is a p5 function [`getURLParams()`](https://p5js.org/reference/#/p5/getURLParams)
which works like this:
```javascript
const { pollId } = getURLParams();
console.log(pollId)
```
and after accessing the pollID we can fetch the necessary details.

**Comment by shiffman** [comment]
I like the idea of using `getURLParams()`! @jriegraf given all the recent changes do you want to update this pull request?

**Comment by shiffman** [comment]
Hmm, I think maybe these changes got implemented now in more recent pull requests, sorry for not getting to this fast enough and mis-managing all these contributions!! Should I close this one?

**Comment by jriegraf** [comment]
Hey Dan, don't worry, I'll contribute another time. Yes, I think these changes are no longer relevant and can therefore we can close this pr.

**Pull request closed without merging**
