### PR TITLE
combined footers + added gradients

### PR DESCRIPTION
**Pull request by ShawKai91**
added my changes to the merge

modified readme

combined similar features

sorry for the long list of commits i merged a new fork from the upstream(your repo) witch apparently caused it to remember them

### CODE REVIEW

**Comment by shiffman** [comment]
Oooops! I merged #72 first and there are now some conflicts, any chance you might be able to update @ShawKai91?

**Comment by ShawKai91** [comment]
updated

**Comment by shiffman** [comment]
This good to merge now?

**Comment by ShawKai91** [comment]
yes good to go  @shiffman

**Pull request merged**
