### PR TITLE
New options for view control

### PR DESCRIPTION
**Pull request by elunico**
Hi, I hope I'm not being annoying make many pull requests and changes 😓 but I changed a couple of things from the last time. 

First I noticed new options for changing to overlay were on top of my options for views, so I consolidated them 

I added a close button so that you can dismiss the view options if they are in the way. 

I changed the way the "no gradient" option looks so it has color instead of just being black, but I hope it will be easier to see. Colors come from [Coding Train Colors](https://coding-train-colors.now.sh). 

Since the "overlay" view option also deleted the element that contained the links to other options, I removed all the options except "overlay view". My reasoning is that once the links disappear you still have to refresh the page to get the normal view back so the extra links didn't seem to help. 

The only thing missing is the completely monochrome, single color progress bar option which was removed when I consolidated all the code. I didn't want to keep adding to this and have a gigantic pull request, but I would be happy to add back that functionality if you like the rest of what I did and still want it.

I enjoy working on this project for fun and I hope I am not causing trouble. Feel free to ignore this very long PR if its too much or not what you're looking for. Thank you 🚂 🌈

### CODE REVIEW

**Comment by elunico** [comment]
Once again providing some context. The background color change does not seem to work in the browser, but I used the same code that was present for changing the background and I can see that it works by examining the CSS.

Normal Rainbow
Screen Shot 2020-12-06 at 12 03 25 PM

One non-rainbow option
Screen Shot 2020-12-06 at 12 03 36 PM

another non-rainbow option
Screen Shot 2020-12-06 at 12 03 29 PM

**Comment by ShawKai91** [comment]
Im liking your implantation more then mine

its surprising how we went about it different but were so close

**Comment by elunico** [comment]
Thank you. I'm sorry I should have checked to see what people had already started. I felt unsatisfied with my first attempt it wasn't good looking. 

I really haven't done much collaborative development so I mean no offense in having done the same thing. 

I only united the controls because they were overlapping. We did have very similar approaches but using the URL was not something I would have thought of at all but it's a great idea! I will definitely keep that approach in mind as well in the future.

**Comment by ShawKai91** [comment]
Ive gone and added the cool gradient thing to mine if that's OK

**Comment by elunico** [comment]
Of course! I'm glad you like it.

**Comment by ShawKai91** [comment]
yes that sounds like a plan

**Pull request closed without merging**
