### PR TITLE
Style update:

### PR DESCRIPTION
**Pull request by pieterdeschepper**
- Animated rainbow progress bars!
- Remove canvas rendering, using pure html / css
- Filter out _id serverside
- Responsive, so you can make it as wide as you want

### CODE REVIEW

**Comment by shiffman** [comment]
oooooh, I love this idea!!! can you fix the merge conflicts by any chance? Would you be able to post as a comment a screenshot / gif of what it should look like so I can check?

**Comment by shiffman** [comment]
@all-contributors please add @pieterdeschepper for design and code!

**Comment by shiffman** [comment]
@all-contributors please add @pieterdeschepper for design and code!

**Comment by pieterdeschepper** [comment]
Merge conflicts have been resolved. This is what it looks like:
https://take.ms/KhWOG

**Comment by shiffman** [comment]
Awesome! Merging now! One thing I should note is that we probably shouldn't include green in the design as it would be keyed out. Or. . even better we can just make the background transparent as there's no need to use a key for this example. I can of course change this later, just noting now!

**Comment by pieterdeschepper** [comment]
Yeah, I used a darker green in the rainbow than the background green, not sure if it would be keyed out, but you could test / finetune this off course. Not sure if/how transparent backgrounds work with OBS so I have not put that in.

**Comment by adriaan1313** [comment]
If you use the OBS built-in 'Browser Source' it natively supports transparency without having to add a chroma key filter.

**Comment by shiffman** [comment]
Thanks @adriaan1313! Yes, this is how I've updated it! @all-contributors add @adriaan1313 for ideas!

**Comment by shiffman** [comment]
I think I fixed it, let's try again. @all-contributors add @adriaan1313 for ideas!

**Pull request merged**
