### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by younesaassila**
- Changes list marker back to standard `1.`
- Removes *Optional* section in favor of a new line in the *Set Up* section
- Changes URL IDs to `snake_case` to improve readability
- Makes the first letter of each list item uppercase
- Adds a new line after every heading to respect convention

### CODE REVIEW

**Comment by ShawKai91** [comment]
id leave the optional because that's more of a troubleshooting step

**Comment by younesaassila** [comment]
It used to be in the *Set Up* section, though. Furthermore I think it's better for the user to type in the command once and not have to worry about encountering an issue and having to come back to the README.

**Comment by ShawKai91** [comment]
I'm not seeing a difference between the links styles

**Comment by younesaassila** [comment]
I'm not sure I understand what you mean. Could you please clarify? Because I didn't change any style.

**Comment by ShawKai91** [comment]
> Changes URL IDs to snake_case to improve readability

ive tried it out to see the difference but couldn't see one
the top two (after)  vs bottom two(before)
Screenshot from 2020-12-22 13-14-07

it could just be me not understanding something
if you can point me in the right direction to understand the logic behind this.

**Comment by younesaassila** [comment]
Weird that you're not seeing the changes. Make sure to have cloned the correct version. What I have changed is the IDs in the last two URLs. Before they were in pascalCase (i.e. {pollId}) but as it's a bit hard to read and as the convention prefers snake_case in URLs I've changed the IDs format to snake_case (i.e. {pollId} -> {poll_id})

**Comment by ShawKai91** [comment]
Screenshot from 2020-12-22 13-32-44
ok the above is the same format as before just adding an underscore

**Comment by younesaassila** [comment]
Also all letters in lower case. Make sure to correctly merge in my changes if you're trying to test them as I can see on your screenshot you don't have those merged.

**Comment by ShawKai91** [comment]
i think pollId is refering to a varibale because i get this
Screenshot from 2020-12-22 13-43-38
clicked on your readme

**Comment by younesaassila** [comment]
Of course it refers to a parameter **that's why it's between curly brackets {}**

**Comment by ShawKai91** [comment]
still dont understand the logic

**Comment by younesaassila** [comment]
There's really nothing to understand. URL parameters are, by convention, between brackets and in snake_case. It's all about conventions.

**Comment by ShawKai91** [comment]
Screenshot from 2020-12-22 13-48-16
ok still same formatting now with lowercase

still not understanding

**Comment by younesaassila** [comment]
I'm sorry but I can't help you if you don't tell me what you don't understand.

**Comment by ShawKai91** [comment]
i guess sense those links don't work i guess it doesn't mater how there formatted

**Comment by younesaassila** [comment]
They work but you need to **replace the parameters by their values**, that's the point of parameters, they can vary like variables.
The format, like I told you, is snake_case by **convention**.

**Comment by ShawKai91** [comment]
ok now im confused by why there links to begin with

**Comment by younesaassila** [comment]
Because the doc has to list all available endpoints/routes and specify available parameters (if any) for each route.

**Comment by ShawKai91** [comment]
ok sorry for my confusion the bulk of my experience in programing is in quickbasic

**Comment by younesaassila** [comment]
No problem!

**Pull request merged**
