### PR TITLE
updated ui 

### PR DESCRIPTION
**Pull request by manthanabc**
now the option come on seprate lines also the train looks a bit better
working

### CODE REVIEW

**Comment by manthanabc** [comment]
now vote and view are seprate things needs some work tho

**Comment by manthanabc** [comment]
Plus can I get the hacktoberfest-acepted label 😅

**Comment by shiffman** [comment]
I love this and would like to merge it, would you mind updating! If you need help please let us know! 💖

**Comment by shiffman** [comment]
Sorry we were too slow about this @manthanabc! Thank you for your contribution!!

**Comment by shiffman** [comment]
@all-contributors please add @manthanabc  for code and design

**Pull request closed without merging**
