### PR TITLE
Added code style rules (Prettier, Eslint & Husky)

### PR DESCRIPTION
**Pull request by Samuel-Martineau**
I see a lot of Pull requests saying things like "added a missing semicolon" (see #40), so I figured out it would be better if it was automated. This pull request adds [prettier](https://prettier.io/) for code style, [eslint](https://eslint.org/) for code linting (most rules are currently disabled in the client code as there seems to be a lot of temporary code) and [husky](https://typicode.github.io/husky/#/) to automatically execute prettier and eslint before commiting.

_P.S.: English is not my main language, so please pardon any English mistakes_

### CODE REVIEW

**Comment by shiffman** [comment]
Ooooh, I love this! I want to develop skills for how to manage code styles better! Maybe I can learn this workflow and make a video about it. 

One small nitpick is I think I like single quotes over double quotes? Should I change my thinking? It's not a dealbreaker for me!

**Comment by Samuel-Martineau** [comment]
I also prefer single quotes, but the code base currently uses double quotes and I wanted as little disruption as possible

**Comment by shiffman** [comment]
> I also prefer single quotes, but the code base currently uses double quotes and I wanted as little disruption as possible

Hah! Ok! I'll merge and can change to single later!

**Comment by Samuel-Martineau** [comment]
It's a really easy change: you just need to change `singleQuotes` from `false` to `true` in `.prettierrc`.

**Pull request merged**
