### PR TITLE
Particular Poll-View via optional URL-Parameters

### PR DESCRIPTION
**Pull request by foxytocin**
Here we go ... implements optional URL-Parameter to set the visual representation. That was a little tricky because of pug. I wasn't able the pass the variables directly to the footer.pug (the options menu). Therefore i've used a data-attribute within the poll.pug (_template(data-styling=styling)_) to pass the styling-attributes from the url-query-parameters around.

If url-query-parameters are submitted the localStorage attributes of _font-simple_, _no-gradient_ and _overlay-on_ are deleted and the url-query-parameters are prioritized to set the visual look.

**Monotone Gradient**
Parameter _monotone_ accepts a boolean
```
monotone=true
monotone=false
```

**Simple Font Option**
Parameter _simple_ accepts a boolean
```
simple=true
simple=false
```

**Overlay Option**
Parameter _transparent_ accepts a boolean or a number (0 - 100)
_true_ will be cast to 100 and _false_ will be cast to 0
Values ​​between 0 and 100 reflect percentages and determine the level of transparency
```
transparent=true
transparent=false
transparent=0
transparent=100
```
- transparent=100 -> background: rgba(255, 255, 255, 0);
- transparent=70  -> background: rgba(255, 255, 255, 0.3);
- transparent=50  -> background: rgba(255, 255, 255, 0.5);
- transparent=20  -> background: rgba(255, 255, 255, 0.8);
- transparent=0  -> background: rgba(255, 255, 255);

**Endpoint**
```
/poll/id?monotone=true&simple=true&transparent=true
/poll/id?monotone=true&simple=true&transparent=100
```

URL Parameters for OBS Overlay by Andreas Fuchs https://anfuchs.com

Greetings Andi

### CODE REVIEW

**Comment by shiffman** [comment]
Wow, this is amazing!

**Comment by shiffman** [comment]
Ooops, I decided to merge your pull requests in reverse chronological order but now there is a conflict! Happy to take a look myself but let me know if you have a chance to review the conflicts, thank you!!

**Comment by foxytocin** [comment]
@shiffman Fortunately, I'm online right now and can look at it. I think it should fit that way. After the merge, I would also look at it again and correct it if the indentations in the .pug are not quite correct. Overall, I think that's how it works.

**Comment by shiffman** [comment]
Ok, merging!

**Pull request merged**
