### PR TITLE
Add dev script to run nodemon

### PR DESCRIPTION
**Pull request by BeeryShklar**
Useful for debugging...

### CODE REVIEW

**Comment by Melvin-Abraham** [comment]
@BeeryShklar This doesn't seem to work for some reason even though it is installed as a dev dependency: `'nodemon' is not recognized as an internal or external command`.

As per README.md for `nodemon`:

> ```
> npm install --save-dev nodemon
> ```
>
> With a local installation, nodemon will not be available in your system path. Instead, the local installation of nodemon can be run by calling it from within an npm script (such as `npm start`) or using `npx nodemon`.

I have tried to replace the `start` script to `nodemon index.js` as well but it still doesn't work. I know installing it globally will also work but if there's anyway to get it working as dev dependency, that would be great.

**Comment by BeeryShklar** [comment]
This is the standard way to do this. Did you try `npm i`?

**Comment by Melvin-Abraham** [comment]
Yes, I tried that as well. No different from what I had...

**Comment by BeeryShklar** [comment]
When I uninstalled nodemon globally I also got this error. Anyone else knows what to do?

**Pull request merged**
