### PR TITLE
Minor refactoring, cleaned up poll_id and getPollId(), modified README.md

### PR DESCRIPTION
**Pull request by D-T-666**
made README look better
**old:**
1. clone repository
2. run npm install
3. run npm run dev
4. un comment /index.js [14 // createNewPoll();], save.
5. change /public/sketch.js [7 let poll_id = "changeThis" ] to the one found in database.db
6. comment /index.js [14 createNewPoll();], save.

**new:**
1. clone repository
2. run `npm install`
3. run `npm run dev`
4. un comment **/index.js** line 14 `// createNewPoll();`, save.
5. change **/public/sketch.js** line 7 `let poll_id = "changeThis"` to the one found in **/database.db**
6. comment **/index.js** line 14 `createNewPoll();`, save.

`getPollId()` now prompts the user to input a poll id, and if no id is provided defaults to a `default_poll_id` variable.

also cleaned up some for loops with unnecessary variables and added missing semicolons, capitalization in comments, and spacing. (only in `public/sketch.js` though)

### CODE REVIEW

**Comment by ShawKai91** [comment]
added it to mine now if only we could get poll id from the database

**Comment by shiffman** [comment]
Hey, appreciate this! Do you want to resolve conflicts and resubmit?

**Comment by shiffman** [comment]
Ah, I was too slow and maybe now this pull request is outdated? Should I close it? Many apologies @D-T-666, thank you so so much for contributing!!!

**Comment by ShawKai91** [comment]
it should have ben part of #28 so yes this one is closed

**Comment by shiffman** [comment]
@all-contributors add @D-T-666 for code and ideas

**Comment by shiffman** [comment]
Thanks @ShawKai91 I merged a bunch of stuff and resolved some conflicts so might have messed things up, feel free to check! Thank you so much for helping with all of this!

**Comment by shiffman** [comment]
@all-contributors please add @ShawKai91 for code and ideas

**Pull request closed without merging**
